const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
let config=null,capture=null,profiles=[],live=false,busy=false,controller=null,generation=0;
const ms=v=>Number.isFinite(v)?`${(v/1000).toFixed(2)} с`:'нет данных';
const bytes=v=>Number.isFinite(v)&&v>0?`${(v/1073741824).toFixed(2)} GiB`:'нет данных';
const label=v=>({correct:'факты совпали',partial:'частично',missing:'факты не совпали',lost_answer:'потерянный ответ',refusal:'отказ',supported:'поддержан контекстом',unsupported:'не поддержан',unknown:'нет ответа',technical_error:'технический сбой',contract_error:'ошибка контракта'}[v]??v??'не оценено');
const profileById=id=>profiles.find(p=>p.id===id);
function status(text,bad=false){$('status').textContent=text;$('status').className=bad?'error':'';}
function recordingOffset(){const h=document.body.classList.contains('recording')?($('recordBar').getBoundingClientRect?.()?.height??0):0;document.documentElement?.style?.setProperty('--record-bar-height',`${h}px`);}
if(typeof ResizeObserver==='function')new ResizeObserver(recordingOffset).observe($('recordBar'));globalThis.addEventListener?.('resize',recordingOffset);
function navigate(id){document.querySelectorAll('[data-step]').forEach(b=>b.classList.toggle('selected',b.dataset.step===id));$('recordCaption').textContent={intro:'Сохраняем качество ответа и проверяем цену результата',settings:'Меняем параметры генерации; документы и поиск сохраняем',compare:'Один вопрос и одинаковый контекст — два реальных ответа',results:'Все прогоны, включая отказы и ошибки, входят в сравнение',conclusion:'Выбор профиля опирается на измерения и ограничения'}[id];recordingOffset();$(id).scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('[data-step],[data-next]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.step||b.dataset.next)));
function recording(on){document.body.classList.toggle('recording',on);$('recordBar').hidden=!on;$('record').setAttribute('aria-pressed',String(on));$('record').textContent=on?'Обычный вид':'Режим записи';recordingOffset();}
$('record').addEventListener('click',()=>recording(!document.body.classList.contains('recording')));
function controls(){$('examples').disabled=busy||!capture;$('profile').disabled=busy||!profiles.some(p=>p.id!=='baseline');$('repeat').disabled=busy||!capture||live;$('question').disabled=busy||!config;$('question').readOnly=!live;$('ask').disabled=busy||!(live||capture)||!$('profile').value;$('reset').disabled=busy;$('stop').disabled=!busy;}
function clearView(){$('context').replaceChildren(node('p','Покажите сравнение.'));$('baselineAnswer').replaceChildren(node('p','Выберите вопрос и покажите прогон.'));$('optimizedAnswer').replaceChildren(node('p','Здесь появится результат кандидата.'));$('raw').textContent='';$('stages').hidden=true;['embedding','retrieval','baseline','optimized'].forEach(s=>{$(s+'Stage').className='';$(s+'Stage').textContent={embedding:'Эмбеддинг',retrieval:'Поиск',baseline:'Исходный профиль',optimized:'Кандидат'}[s];});}
function contextView(chunks){$('context').replaceChildren();if(!chunks?.length){$('context').append(node('p','Подходящих фрагментов не найдено.'));return;}chunks.forEach((c,i)=>{const d=node('details');d.append(node('summary',`${i+1}. ${c.source} · ${Number.isFinite(c.similarity)?'cosine '+c.similarity.toFixed(3):'сходство не записано'}`),node('p',c.section,'note'),node('p',c.text),node('p',c.chunk_id,'note'));$('context').append(d);});}
function answerView(target,result,assessment){target.replaceChildren();if(!result){target.append(node('p','Для этой пары сохранённого прогона нет.','error'));return;}if(result.error){target.append(node('p',`${({contract:'Ответ не прошёл проверку формата и источников',incomplete:'Модель не завершила ответ',technical:'Ошибка обращения к модели'}[result.error_kind]||'Ошибка')}: ${result.error}`,'error'));}else if(!result.answer){target.append(node('p','Ответ не получен.','error'));}else{const a=result.answer;if(a.unknown)target.append(node('p',result.reason==='empty_context'?'Поиск не нашёл подходящих фрагментов; генерация не выполнялась.':'Модель отказалась отвечать по имеющемуся контексту.','note'));target.append(node('p',a.answer||a.clarification||'Текст ответа пуст.','answerText'));if(a.clarification&&a.answer)target.append(node('p',a.clarification));(a.sources||[]).forEach(s=>{const d=node('details');d.append(node('summary',`${s.source} · ${s.section||s.chunk_id||'источник'}`),node('blockquote',s.quote,'quote'));target.append(d);});}
 target.append(node('p',`Полное время: ${ms(result.total_ms)} · поиск: ${ms(result.retrieval_ms)} · генерация: ${ms(result.generation_ms)}`,'note'));
 const rss=result.resources?.rss_max_kib;target.append(node('p',`Максимум суммы RSS runner за время запроса (включая смену профиля): ${bytes(Number.isFinite(rss)?rss*1024:null)}`,'note'));
 if(live&&!assessment)target.append(node('p','Время этого живого запроса может включать загрузку или смену модели и embedding. Это не медиана тёплой серии ниже.','note'));
 if(assessment){target.append(node('p',`${label(assessment.facts)} · ${label(assessment.semantic)}`,'note'));if(assessment.reason)target.append(node('p',assessment.reason,'note'));}else target.append(node('p','Смысловая оценка этого нового ответа ещё не выполнена.','note'));
}
function renderPair(data,saved=false){contextView(data.context||[]);answerView($('baselineAnswer'),data.baseline,data.baselineAssessment);answerView($('optimizedAnswer'),data.optimized,data.optimizedAssessment);$('candidateTitle').textContent=profileById(data.profile)?.label||data.profile||'Кандидат';$('raw').textContent=JSON.stringify(data,null,2);if(saved)status('Показана сохранённая пара реальных прогонов. Новые вызовы модели не выполнялись.');else status('Парное сравнение завершено. Источники и исходные данные доступны ниже.');}
function selectedQuestion(){return capture?.questions?.find(q=>q.id===$('examples').value);}
function repeats(){const values=[...new Set((capture?.runs||[]).filter(r=>r.id===$('examples').value&&r.profile===$('profile').value).map(r=>r.repeat))].sort((a,b)=>a-b);const prev=$('repeat').value;$('repeat').replaceChildren(...values.map(v=>{const o=node('option',`Повтор ${v}`);o.value=v;return o;}));if(values.some(v=>String(v)===prev))$('repeat').value=prev;}
function syncExpectation(){const q=selectedQuestion();$('expectation').textContent=q&&$('question').value.trim()===q.question.trim()&&q.expectation?`Ожидаемый факт / поведение: ${q.expectation}`:'';}
function fillQuestion(){const q=selectedQuestion();if(q)$('question').value=q.question;syncExpectation();repeats();clearView();status(live?'Можно запустить настоящий парный запрос на Mac.':'Выберите профиль и покажите сохранённое сравнение.');controls();}
$('question').addEventListener('input',()=>{if(live){syncExpectation();clearView();status('Вопрос изменён. Запустите новое сравнение.');}});
$('examples').addEventListener('change',fillQuestion);$('profile').addEventListener('change',()=>{repeats();clearView();controls();});$('repeat').addEventListener('change',()=>{clearView();status('Покажите выбранный повтор.');});
function stage(kind){const stages=['embedding','retrieval','baseline','optimized'],at=stages.indexOf(kind);$('stages').hidden=false;stages.forEach((s,i)=>$(s+'Stage').className=i<at?'done':i===at?'active':'');status({embedding:'Создаём локальный эмбеддинг вопроса…',retrieval:'Ищем фрагменты в неизменном индексе…',baseline:'Исходный профиль формирует ответ…',optimized:'Кандидат отвечает по тем же фрагментам…'}[kind]);}
$('stop').addEventListener('click',()=>{generation++;controller?.abort();controller=null;busy=false;clearView();status('Запрос отменён. Незавершённые ответы не показаны; можно повторить сравнение.');controls();});
$('reset').addEventListener('click',()=>{generation++;controller?.abort();controller=null;busy=false;if(capture){$('examples').selectedIndex=0;$('profile').value=capture.summary?.winner||config.winner||profiles.find(p=>p.id!=='baseline')?.id;fillQuestion();}else{clearView();$('question').value='';controls();}document.querySelectorAll('details').forEach(d=>d.open=false);navigate('intro');status('Демонстрация сброшена. Выберите вопрос и покажите сравнение.');});
$('ask').addEventListener('click',async()=>{if(busy)return;if(!live){const id=$('examples').value,repeat=Number($('repeat').value),profile=$('profile').value;const b=capture?.runs.find(r=>r.id===id&&Number(r.repeat)===repeat&&r.profile==='baseline'),o=capture?.runs.find(r=>r.id===id&&Number(r.repeat)===repeat&&r.profile===profile);renderPair({question:selectedQuestion()?.question,context:o?.result?.context||b?.result?.context||[],baseline:b?.result,optimized:o?.result,profile,repeat,baselineAssessment:b?.assessment,optimizedAssessment:o?.assessment},true);return;}
 syncExpectation();const question=$('question').value.trim();if(!question){status('Введите вопрос.',true);return;}if(new TextEncoder().encode(question).length>4000){status('Вопрос превышает 4000 байт UTF-8. Сократите его.',true);return;}const token=++generation;controller=new AbortController();busy=true;clearView();controls();status('Подключаемся к локальному приложению…');
 try{const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,profile:$('profile').value}),signal:controller.signal});if(!response.ok){let message=`HTTP ${response.status}`;try{const d=await response.json();message=d.error||message;}catch{}throw Error(message);}if(!response.body)throw Error('Сервер не вернул поток ответа.');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',finished=false;const receive=line=>{if(!line.trim()||token!==generation)return;const e=JSON.parse(line);if(['embedding','retrieval','baseline','optimized'].includes(e.event))stage(e.event);if(e.event==='context')contextView(e.data);if(e.event==='error')throw Error(e.data?.error||e.data?.message||String(e.data));if(e.event==='result'){finished=true;renderPair(e.data);['embedding','retrieval','baseline','optimized'].forEach(s=>$(s+'Stage').className='done');for(const [id,r] of [['baseline',e.data.baseline],['optimized',e.data.optimized]])if(!r?.attempts?.length){$(id+'Stage').className='';$(id+'Stage').textContent=(id==='baseline'?'Исходный профиль':'Кандидат')+' — без генерации';}}};
 while(true){const {done,value}=await reader.read();if(token!==generation){await reader.cancel();break;}buffer+=decoder.decode(value,{stream:!done});let cut;while((cut=buffer.indexOf('\n'))>=0){receive(buffer.slice(0,cut));buffer=buffer.slice(cut+1);}if(done){receive(buffer);break;}}if(!finished&&token===generation)throw Error('Соединение закрыто до получения результата.');
 }catch(e){if(token===generation){controller?.abort();status(e.name==='AbortError'?'Запрос отменён.':`Ошибка сравнения: ${e.message}`,e.name!=='AbortError');}}
 finally{if(token===generation){busy=false;controller=null;controls();}}
});
function table(headers,rows){const wrap=node('div',undefined,'tableWrap'),t=node('table'),head=node('thead'),h=node('tr');wrap.setAttribute('tabindex','0');wrap.setAttribute('aria-label','Таблица результатов; все столбцы доступны при горизонтальной прокрутке');headers.forEach(x=>h.append(node('th',x)));head.append(h);t.append(head);const body=node('tbody');rows.forEach(row=>{const tr=node('tr');row.forEach((x,i)=>{const td=node('td',x);td.dataset.label=headers[i];tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);return wrap;}
function chartView(){
 const kind=$('chartMetric').value||'quality',summaries=capture?.summary?.profiles||[];
 const comparable=capture?.summary?.comparable_profiles||[],pairs=capture?.summary?.comparable_supported_pairs||0,comparatorReady=comparable.length>=2&&pairs>0;
 const value=s=>kind==='time'?(comparatorReady&&comparable.includes(s.id)?s.successful_median_ms:null):kind==='memory'?s.memory_bytes:s.correct_supported;
 const maximum=kind==='quality'?Math.max(1,...summaries.map(s=>s.total||0)):Math.max(1,...summaries.map(s=>value(s)||0));$('chart').replaceChildren();
 $('chartNote').textContent=kind==='time'&&!comparatorReady?'Нет сопоставимых правильных содержательных пар для сравнения исходного профиля с допустимыми кандидатами. Ускорение полезных ответов не подтверждено.':kind==='quality'?'Больше — лучше. Корректные отказы показаны отдельно в таблице.':kind==='time'?`Сравниваем ${pairs} одинаковых пар вопрос/повтор с правильным поддержанным ответом в профилях: ${comparable.map(id=>profileById(id)?.label||id).join(', ')}. Меньше — быстрее на этих парах; у остальных профилей сопоставимое время не показано.`:'Меньше — меньше выделение выбранному генератору; сумма RSS и размер весов на диске — отдельные показатели.';
 for(const s of summaries){const row=node('div',undefined,'chartRow'),n=value(s);const meter=node('meter');meter.min=0;meter.max=maximum;meter.value=n||0;meter.setAttribute('aria-label',profileById(s.id)?.label||s.id);row.append(node('span',profileById(s.id)?.label||s.id),meter,node('strong',kind==='time'?ms(n):kind==='memory'?bytes(n):`${n} / ${s.total}`));$('chart').append(row);}
}
$('chartMetric').addEventListener('change',chartView);
function report(){const summaries=capture?.summary?.profiles||[],winner=capture?.summary?.winner||config.winner,p=profileById(winner),s=summaries.find(s=>s.id===winner);$('winnerTitle').textContent=p?`Выбранный профиль: ${p.label}`:'Выбор профиля не записан';$('winnerReason').textContent=capture?.summary?.reason||'Обоснование выбора в данных отсутствует.';if(s){const values=[[`${s.correct_supported} / ${s.total}`,'правильных ответов с поддержкой контекстом'],[ms(s.successful_median_ms),'медиана успешных сопоставимых ответов'],[`${s.errors}`,'технических / форматных ошибок']];$('metrics').replaceChildren(...values.map(([v,l])=>{const n=node('div',undefined,'metric');n.append(node('strong',v),node('span',l));return n;}));}
 $('coldTiming').textContent=(capture.summary?.cold_controls||[]).map(c=>`Отдельный холодный контроль (${profileById(c.profile)?.label||c.profile}): полное время ${ms(c.total_ms)}, загрузка embedding ${ms(c.embedding_load_ms)}, генератора ${ms(c.generation_load_ms)}.`).join(' ')+' Холодные контроли не входят в медианы тёплой серии.';
 $('evaluation').replaceChildren(table(['Профиль','Всего / валидных','Верных ответов','Верных отказов','Потерянных / неподдержанных','Ошибок','Медиана всех','Медиана успешных','Выделение генератору / сумма RSS runner'],summaries.map(s=>[profileById(s.id)?.label||s.id,`${s.total} / ${s.valid}`,s.correct_supported,s.correct_refusals,`${s.lost_answers} / ${s.unsupported}`,s.errors,ms(s.median_ms),ms(s.successful_median_ms),`${bytes(s.memory_bytes)} / ${bytes(Number.isFinite(s.rss_max_kib)?s.rss_max_kib*1024:null)}`])));
 $('allRuns').replaceChildren(table(['Вопрос','Профиль','Повтор','Факты / смысл','Время','Ошибка / обоснование'],(capture.runs||[]).map(r=>[r.id,profileById(r.profile)?.label||r.profile,r.repeat,`${label(r.assessment?.facts)} / ${label(r.assessment?.semantic)}`,ms(r.result?.total_ms),r.result?.error||r.assessment?.reason||'—'])));
 chartView();const limitations=capture.meta?.limitations;$('limitations').textContent=Array.isArray(limitations)?limitations.join(' '):typeof limitations==='string'?limitations:'';
}
async function getJSON(path){const r=await fetch(path);if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.json();}
async function init(){recording(new URLSearchParams(location.search).has('record'));try{config=await getJSON('./config.json');if(!['live','replay'].includes(config.mode))throw Error('Неизвестный режим приложения.');live=config.mode==='live';$('mode').textContent=live?'Живой запуск на Mac':'Сохранённые реальные прогоны';$('disclosure').textContent=live?'Каждый запуск выполняет поиск и две последовательные генерации локально на этом Mac.':'Публичная интерактивная витрина сохранённых измерений. Новые запросы модели здесь не выполняются.';$('ask').textContent=live?'Запустить до / после':'Показать сохранённое сравнение';$('inputNote').textContent=live?'Введите свой вопрос или выберите пример. Лимит — 4000 байт UTF-8.':'Здесь доступны вопросы реального измерения. Произвольный вопрос можно задать в локальной версии на Mac.';
 try{capture=await getJSON('./showcase.json');}catch(e){if(!live)throw e;$('evaluation').textContent='Сохранённые измерения пока недоступны.';}
 profiles=capture?.profiles?.length?capture.profiles:config.profiles||[];const candidates=profiles.filter(p=>p.id!=='baseline');$('profile').replaceChildren(...candidates.map(p=>{const o=node('option',p.label||p.id);o.value=p.id;return o;}));$('profile').value=capture?.summary?.winner||config.winner||candidates[0]?.id;if(!$('profile').value&&candidates.length)$('profile').selectedIndex=0;
 $('profileCards').replaceChildren(...profiles.map(p=>{const c=node('div',undefined,'profileCard');const quant=capture?.meta?.model_details?.[p.model]?.details?.quantization_level;const prompt=node('details');prompt.append(node('summary','Точный промпт'),node('pre',p.prompt));c.append(node('h3',p.label||p.id),node('p',p.model+(quant?' · '+quant:'')),node('p',`temperature ${p.temperature} · вывод ${p.num_predict} · контекст ${p.num_ctx}`,'values'),node('p',p.prompt===profileById('baseline')?.prompt?'Исходная инструкция дня 28.':'Короткая инструкция: прямой ответ, подтверждённый выбранной цитатой.'),prompt);return c;}));$('identity').textContent=JSON.stringify({config,meta:capture?.meta,profiles},null,2);
 if(capture){$('examples').replaceChildren(...capture.questions.map(q=>{const o=node('option',q.question);o.value=q.id;return o;}));report();fillQuestion();}else{$('examples').replaceChildren(node('option','Свободный вопрос'));status('Введите вопрос: модели работают локально на Mac.');}controls();if(!candidates.length)status('Профили сравнения отсутствуют. Запуск недоступен.',true);
 }catch(e){status(`Не удалось загрузить витрину: ${e.message}`,true);$('mode').textContent='Данные недоступны';$('disclosure').textContent='Обновите страницу после проверки данных приложения.';config=null;controls();}}
init();
