const $=id=>document.getElementById(id);
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
let live=false,capture=null,controller=null,generation=0;
const ms=v=>`${(v/1000).toFixed(2)} с`;
const label=v=>({correct:'совпали',partial:'частично',missing:'не совпали',lost_answer:'ответ пропущен',refusal:'отказ',supported:'поддержан',unsupported:'не поддержан',unknown:'нет ответа',pending:'ожидает проверки',not_applicable:'не применимо',technical_error:'технический сбой',contract_error:'ошибка контракта'}[v]??v);
function status(text,bad=false){$('status').textContent=text;$('status').className=bad?'error':'';}
function clearView(){['context','answer','comparison'].forEach(id=>$(id).replaceChildren());$('raw').textContent='';$('timing').textContent='';['embedding','retrieval','generation'].forEach(s=>$(s+'Stage').className='');$('generationStage').textContent='Генерация ответа';}
function stage(kind){const stages=['embedding','retrieval','generation'],at=stages.indexOf(kind);stages.forEach((s,i)=>$(s+'Stage').className=i<at?'done':i===at?'active':'');status({embedding:'Создаём локальный эмбеддинг вопроса…',retrieval:'Ищем подходящие документы в локальном индексе…',generation:'Qwen формирует ответ по найденным документам…'}[kind]);}
function contextView(chunks){$('context').replaceChildren();if(!chunks.length){$('context').append(node('p','Подходящих фрагментов не найдено.'));return;}chunks.forEach((c,i)=>{const d=node('details');d.append(node('summary',`${i+1}. ${c.source} · cosine ${c.similarity.toFixed(3)}`),node('p',c.section,'note'),node('p',c.text),node('p',c.chunk_id,'note'));$('context').append(d);});}
function answerView(target,r){target.replaceChildren();if(r.error){target.append(node('p',`${r.error_kind==='contract'?'Ошибка контракта ответа':r.error_kind==='incomplete'?'Незавершённый ответ':'Техническая ошибка'}: ${r.error}`,'error'));return;}if(!r.answer){target.append(node('p','Генерация не выполнялась.'));return;}
 const a=r.answer;target.append(node('p',a.answer,'answerText'));if(a.unknown)target.append(node('p',a.clarification));a.sources.forEach(s=>{target.append(node('p',`${s.source} · ${s.section}`,'note'),node('p',s.quote,'quote'),node('p',s.chunk_id,'note'));});if(r.checks){target.append(node('p',`Эталонные факты: ${label(r.checks.facts)} · смысловая оценка: ${label(r.checks.semantic)}`,'note'));if(r.checks.reason)target.append(node('p',r.checks.reason,'note'));}
}
function comparisonView(question){$('comparison').replaceChildren();const c=capture?.comparisons.find(x=>x.question===question);if(!c){$('comparison').append(node('p','Для этого вопроса архивного сравнения нет.'));return;}if(!c.cloud.answer_call){$('comparison').append(node('p','В облачном архиве для этого вопроса был пустой контекст: генерация не выполнялась.'));return;}
 $('comparison').append(node('p','Одинаковые входные сообщения и фрагменты; сравнивается генерация, а не два разных поиска.','note'));const grid=node('div',undefined,'grid'),left=node('div'),right=node('div');left.append(node('h3','Qwen · локальный замер'));right.append(node('h3','DeepSeek · архив 01.10'));
 const la=node('div'),ca=node('div');answerView(la,c.local);answerView(ca,{answer:c.cloud.answer,checks:{facts:c.cloud.checks.fact_outcome,semantic:c.cloud.semantic.verdict}});left.append(la,node('p',`Генерация с повторами: ${ms(c.local.generation_ms)}`,'note'));const duration=c.cloud.answer_call.attempts.reduce((s,a)=>s+a.duration_ms,0);right.append(ca,node('p',`Генерация с повторами: ${ms(duration)}`,'note'));grid.append(left,right);$('comparison').append(grid);const d=node('details');d.append(node('summary','Одинаковый вход сравнения'),node('pre',JSON.stringify(c.messages,null,2)));$('comparison').append(d);
}
function render(r,saved=false){contextView(r.context);if(r.error&&!r.context.length)$('context').replaceChildren(node('p','Контекст не получен: обработка завершилась ошибкой.'));answerView($('answer'),r);$('timing').textContent=`${saved?'Сохранённый прогон · ':''}поиск с эмбеддингом ${ms(r.retrieval_ms)} · генерация ${ms(r.generation_ms)} · всего ${ms(r.total_ms)}`;$('raw').textContent=JSON.stringify(r,null,2);comparisonView(r.question);['embedding','retrieval','generation'].forEach(s=>$(s+'Stage').className=r.error?'':'done');if(!r.attempts?.length){$('generationStage').className='';$('generationStage').textContent='Генерация не выполнялась';}else $('generationStage').textContent='Генерация ответа';status(r.error?(r.error_kind==='contract'?'Модель вернула ответ, нарушающий контракт.':r.error_kind==='incomplete'?'Ответ модели оборван.':'Запрос завершился технической ошибкой.'):saved?'Показан сохранённый результат реального локального прогона.':r.reason==='empty_context'?'Запрос завершён. Подходящих фрагментов нет; локальный отказ без генерации.':'Запрос завершён. Ответ и цитаты проверены по формату и найденным фрагментам.',!!r.error);}
function metrics(){
 if(!capture?.summary)return;const s=capture.summary;
 const values=[[`${s.valid}/${s.total}`,'валидных результатов с ограничением формата'],[`${s.supported}/${s.substantive}`,'содержательных ответов поддержаны контекстом'],[ms(s.median_total_ms),`медиана всех ${s.total} запросов, включая отказы`]];
 $('metrics').replaceChildren(...values.map(([a,b])=>{const n=node('div',undefined,'metric');n.append(node('strong',a),node('span',b));return n;}));
 const breakdown=node('div',undefined,'breakdown');
 const groups=[
  ['Отказы и факты',`Корректных отказов вне базы: ${s.good_refusals}. Пропущенных ответов при наличии факта: ${s.lost_answers}.\nЭталонные факты совпали: ${s.fact_counts.correct}; частично: ${s.fact_counts.partial}; не совпали: ${s.fact_counts.missing}.`],
  ['Скорость',`Поиск с эмбеддингом: медиана ${ms(s.median_retrieval_ms)}, диапазон ${ms(s.min_retrieval_ms)}–${ms(s.max_retrieval_ms)}.\nГенерация: медиана ${ms(s.median_generation_ms)}, диапазон ${ms(s.min_generation_ms)}–${ms(s.max_generation_ms)}, только ${s.generation_runs} запросов с вызовом модели.\nПолное время: ${ms(s.min_total_ms)}–${ms(s.max_total_ms)}, все ${s.total} запросов, включая отказы без генерации.`],
  ['Повторяемость',`Одинаковый итоговый JSON во всех трёх повторах: ${s.identical_groups}/${s.groups} вопросов. Технических сбоев в основном прогоне: ${s.errors}. Одинаковый ответ может быть неверным.`],
  ['Архивное сравнение',`Валидных ответов Qwen: ${s.comparison_valid}/${s.comparison_calls}. Ошибок контракта: ${s.comparison_contract_errors}; технических или незавершённых: ${s.comparison_technical_errors}. Это отдельные запросы; в основной прогон они не входят.`],
  ['Холодный контроль',`После выгрузки обеих моделей: ${ms(s.cold_control_total_ms)} полного времени.\nЗагрузка bge-m3: ${ms(s.cold_embedding_load_ms)}, Qwen: ${ms(s.cold_generation_load_ms)}.`]
 ];
 for(const [title,text] of groups){const item=node('div');item.append(node('h3',title),node('p',text));breakdown.append(item);}
 const w=node('div',undefined,'tableWrap'),table=node('table'),thead=node('thead'),head=node('tr'),headers=['Вопрос','Повтор','Результат','Факты','Смысл','Время'];headers.forEach(x=>head.append(node('th',x)));thead.append(head);table.append(thead);
 const body=node('tbody');capture.runs.forEach(r=>{const tr=node('tr');[r.id,r.repeat,r.result.error?'сбой':r.result.answer.unknown?'отказ':'ответ',label(r.result.checks.facts),label(r.result.checks.semantic),ms(r.result.total_ms)].forEach((x,i)=>{const td=node('td',String(x));td.setAttribute('data-label',headers[i]);tr.append(td);});body.append(tr);});table.append(body);w.append(table);$('evaluation').replaceChildren(breakdown,w);
}
function fillExample(){const q=capture?.questions.find(q=>q.id===$('examples').value);if(q){$('question').value=q.question;comparisonView(q.question);}}
$('examples').addEventListener('change',fillExample);
$('reset').addEventListener('click',()=>{generation++;controller?.abort();controller=null;clearView();$('question').value='';$('ask').disabled=!live&&!capture;$('stop').disabled=true;status('Введите новый вопрос или выберите пример.');});
$('stop').addEventListener('click',()=>{generation++;controller?.abort();controller=null;clearView();$('ask').disabled=false;$('stop').disabled=true;status('Запрос отменён. Можно повторить или выбрать другой вопрос.');});
$('record').addEventListener('click',()=>{$('caption').hidden=!$('caption').hidden;});
$('ask').addEventListener('click',async()=>{
 if(!live){const r=capture?.runs.find(x=>x.id===$('examples').value&&x.repeat===1);if(r)render(r.result,true);return;}
 const question=$('question').value;if(!question.trim()){status('Введите вопрос.',true);return;}if(new TextEncoder().encode(question).length>4000){status('Вопрос слишком длинный: лимит 4000 байт UTF-8, примерно 2000 русских букв.',true);return;}
 const token=++generation;controller=new AbortController();clearView();$('ask').disabled=true;$('stop').disabled=false;status('Проверяем доступность локальных моделей…');
 try{const response=await fetch('/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question}),signal:controller.signal});if(!response.ok){const d=await response.json();throw Error(d.error||`HTTP ${response.status}`);}
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',finished=false;
 const receive=line=>{if(!line.trim()||token!==generation)return;const e=JSON.parse(line);if(['embedding','retrieval','generation'].includes(e.event))stage(e.event);if(e.event==='context')contextView(e.data);if(e.event==='result'){finished=true;render(e.data);}};
 while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let cut;while((cut=buffer.indexOf('\n'))>=0){receive(buffer.slice(0,cut));buffer=buffer.slice(cut+1);}if(done){receive(buffer);break;}}
 if(!finished&&token===generation)throw Error('Соединение закрыто до получения результата.');
 }catch(e){if(token===generation)status(e.name==='AbortError'?'Запрос отменён.':`Техническая ошибка: ${e.message}`,e.name!=='AbortError');}
 finally{if(token===generation){$('ask').disabled=false;$('stop').disabled=true;controller=null;}}
});
async function init(){
 $('caption').hidden=!new URLSearchParams(location.search).has('record');
 try{const r=await fetch('./config.json');if(!r.ok)throw Error('Режим приложения недоступен');const config=await r.json();live=config.mode==='live';$('identity').textContent=JSON.stringify(config,null,2);}catch(e){status(e.message,true);$('disclosure').textContent='Не удалось определить режим приложения. Обновите страницу после проверки сервера.';return;}
 $('mode').textContent=live?'Живой локальный RAG':'Сохранённые прогоны';$('disclosure').textContent=live?'Вы работаете с настоящим локальным RAG на этом Mac. Каждый новый вопрос проходит поиск и генерацию.':'Интерактивная витрина сохранённых реальных локальных прогонов. Эта публичная страница не отправляет новые запросы модели.';$('question').readOnly=!live;$('ask').textContent=live?'Запустить RAG':'Показать сохранённый прогон';
 try{const r=await fetch('./showcase.json');if(!r.ok)throw Error('Сохранённый прогон пока недоступен');capture=await r.json();$('examples').replaceChildren(...capture.questions.map(q=>{const n=node('option',q.question);n.value=q.id;return n;}));$('examples').value='g01';fillExample();metrics();if(!live)$('identity').textContent=JSON.stringify(capture.meta,null,2);}catch(e){$('examples').replaceChildren(node('option','Свободный вопрос'));if(!live)status(e.message,true);}
 $('ask').disabled=!live&&!capture;if(live||capture)status(live?'Введите вопрос: поиск и генерация выполняются на Mac.':'Выберите вопрос и покажите его сохранённый прогон.');
}
init();
