#!/usr/bin/env node

// Builds the human-readable Day 9 result only from the two raw JSONL rows written
// by the live probe. Keep the conclusion deliberately narrow: the fixture checks
// planted markers, not arbitrary conversation quality.
import { readFile } from "node:fs/promises";

const here = new URL(".", import.meta.url);
const input = new URL("compression.jsonl", here);

function fail(message) {
  throw new Error(`day-09 report: ${message}`);
}

function integer(value, label) {
  if (!Number.isInteger(value) || value < 0) fail(`${label} must be a non-negative integer`);
  return value;
}

function money(value, label) {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
    fail(`${label} must be a non-negative number`);
  }
  return `$${value.toFixed(6)}`;
}

function readTotals(report, field) {
  const total = report[field];
  if (!total || typeof total !== "object") fail(`${report.mode}.${field} is missing`);
  return {
    calls: integer(total.calls, `${report.mode}.${field}.calls`),
    prompt: integer(total.promptTokens, `${report.mode}.${field}.promptTokens`),
    cached: integer(total.cachedTokens, `${report.mode}.${field}.cachedTokens`),
    cost: money(total.cost, `${report.mode}.${field}.cost`),
  };
}

function readReport(report) {
  if (!report || typeof report !== "object") fail("each JSONL row must be an object");
  if (typeof report.run !== "string" || report.run === "") fail("run is missing");
  if (report.mode !== "full" && report.mode !== "compressed") fail("unknown mode");
  if (!Array.isArray(report.checks) || report.checks.length === 0) fail(`${report.mode}.checks is missing`);
  const correct = integer(report.correct, `${report.mode}.correct`);
  if (correct > report.checks.length) fail(`${report.mode}.correct exceeds checks`);
  return {
    run: report.run,
    mode: report.mode,
    checks: report.checks.length,
    correct,
    total: readTotals(report, "total"),
    summary: readTotals(report, "summarySpend"),
  };
}

const source = await readFile(input, "utf8");
const rows = source.trim().split("\n").filter(Boolean).map((line, index) => {
  try {
    return readReport(JSON.parse(line));
  } catch (error) {
    fail(`line ${index + 1}: ${error.message}`);
  }
});
if (rows.length !== 2) fail(`expected exactly two reports, got ${rows.length}`);

const full = rows.find((row) => row.mode === "full");
const compressed = rows.find((row) => row.mode === "compressed");
if (!full || !compressed) fail("both full and compressed reports are required");
if (full.run !== compressed.run) fail("the reports are from different probe runs");
if (full.checks !== compressed.checks) fail("the modes ran different check counts");

const quality = compressed.correct >= full.correct
  ? "В этой закрытой фактуре сжатый режим сохранил не меньше маркеров, чем полный."
  : "В этой закрытой фактуре сжатый режим сохранил меньше маркеров, чем полный."
const fullCost = Number(full.total.cost.slice(1));
const compressedCost = Number(compressed.total.cost.slice(1));
const economy = compressedCost < fullCost
  ? `Полная стоимость сжатого прогона ниже на $${(fullCost - compressedCost).toFixed(6)}; в ней уже учтён summary.`
  : compressedCost === fullCost
    ? "Полная стоимость режимов одинакова; одного уменьшения размера ответа для вывода об экономии недостаточно."
    : `Сжатый прогон дороже на $${(compressedCost - fullCost).toFixed(6)} с учётом summary; на этой фактуре его нельзя называть экономией.`;

process.stdout.write(`# Day 9 — live comparison\n\n<!-- Generated by day-09/render-report.mjs from day-09/compression.jsonl.\n     Do not edit measured values by hand. Probe run: ${full.run}. -->\n\nThe same closed dialogue ran twice against DeepSeek: once with complete history and once\nwith the last ten messages verbatim plus a separate summary. Three exact markers check the\nbeginning, middle, and raw tail of this fixture; this is not a general quality score.\n\n| mode | markers | provider calls | input tokens | cached input | total cost | summary calls | summary cost |\n|---|---:|---:|---:|---:|---:|---:|---:|\n| full history | ${full.correct}/${full.checks} | ${full.total.calls} | ${full.total.prompt} | ${full.total.cached} | ${full.total.cost} | ${full.summary.calls} | ${full.summary.cost} |\n| compressed history | ${compressed.correct}/${compressed.checks} | ${compressed.total.calls} | ${compressed.total.prompt} | ${compressed.total.cached} | ${compressed.total.cost} | ${compressed.summary.calls} | ${compressed.summary.cost} |\n\n${quality}\n\n${economy}\n\nThe raw provider reports are in [compression.jsonl](compression.jsonl). Regenerate this file\nafter a new probe with:\n\n\`\`\`bash\nnode day-09/render-report.mjs > day-09/RESULTS.md\n\`\`\`\n`);
